import Head from 'next/head';
import { Inter } from '@next/font/google';
import Navbar from '@/components/Shared/Navbar/Navbar';
import Conference from '@/components/Conference/Conference';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Saarte Investeering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vector.svg" />
      </Head>
      <main className="mx-5">
        <Navbar />
        <Conference />
        {/* <App/> */}
      </main>
    </>
  );
}
